name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-11-jdk
        
    - name: Install Buildozer
      run: pip3 install buildozer
        
    - name: Build APK (with timeout)
      run: |
        timeout 35m buildozer android debug || echo "Build might have timed out but continuing"
      
    - name: Check for APK
      run: |
        if [ -f bin/*.apk ]; then
          echo "APK found!"
          ls -la bin/
        else
          echo "No APK found"
          ls -la
        fi
      
    - name: Upload APK if exists
      uses: actions/upload-artifact@v4
      with:
        name: flux-mobile-apk
        path: bin/*.apk
