name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-11-jdk
        
    - name: Install Buildozer
      run: pip3 install buildozer cython==0.29.33
        
    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug
      
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: flux-mobile-apk
        path: bin/*.apk
