[app]
title = Flux Test
package.name = fluxtest
package.domain = org.test

version = 0.1
version.code = 1

source.dir = .
source.main = main.py

requirements = python3

android.minapi = 21
android.targetapi = 30

[buildozer]
log_level = 2
